
GET http://localhost:8080/contacts

###

GET http://localhost:8080/contacts/650ff3f16625c1740ea260ab

###
GET http://localhost:8080/contacts/6513939bfe29db47f6821dea

###

GET http://localhost:8080/contacts/651393f0fe29db47f6821deb 

//Render Links

//GET All
###
GET https://cse341fall23.onrender.com/contacts
//Get Individual
###
GET https://cse341fall23.onrender.com/contacts/650ff3f16625c1740ea260ab
###
GET https://cse341fall23.onrender.com/contacts/6513939bfe29db47f6821dea
###
GET https://cse341fall23.onrender.com/contacts/651393f0fe29db47f6821deb 


//POST requests
///local
###
POST http://localhost:8080/contacts HTTP/1.1

{
    "firstName": "Quinn",
    "lastName": "Butterfield",
    "email": "qButterfield@email.com",
    "favoriteColor": "Red",
    "birthday": "09/04/95"
}